FILESTORAGE_LOG_LEVEL: "error"
FILESTORAGE_METRICS_COLLECT_DEFAULT: "true"
AUTHORIZATION_API_HOST: "{{ API_HOST_URI }}/api/v3"

ENABLE_FILE_SECURITY_CHECK: "true"
ANTIVIRUS_SERVICE_HOSTNAME: "clamav-svc"
ANTIVIRUS_SERVICE_PORT: "3310"
FILE_STORAGE_SERVICE_HOSTNAME: "http://api-files-svc:4444"
FILES_STORAGE_USE_STREAM_TO_ANTIVIRUS: "true"
