ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apk add --no-cache \
    imagemagick \
    imagemagick-heic \
    imagemagick-jpeg \
    imagemagick-pdf \
    imagemagick-raw \
    imagemagick-svg \
    imagemagick-tiff \
    imagemagick-webp \
    imagemagick-jp2

COPY imagemagic_policy.xml /etc/ImageMagick-7/policy.xml