export enum ErrorType {
	FILE_NOT_FOUND = 'FILE_NOT_FOUND',
	FILE_NAME_EXISTS = 'FILE_NAME_EXISTS',
	FILE_NAME_EMPTY = 'FILE_NAME_EMPTY',
	FILE_TOO_BIG = 'FILE_TOO_BIG',
	PREVIEW_NOT_POSSIBLE = 'PREVIEW_NOT_POSSIBLE',
	FILE_IS_EMPTY = 'FILE_IS_EMPTY',
	STORAGE_LOCATION_TYPE_NOT_EXISTS = 'STORAGE_LOCATION_TYPE_NOT_EXISTS',
	MIME_TYPE_MISMATCH = 'MIME_TYPE_MISMATCH',
	INTERNAL_SERVER_ERROR_STORAGE_LOCATION_DELETE = 'INTERNAL_SERVER_ERROR_STORAGE_LOCATION_DELETE',
	NO_SOURCE_FILE_RECORDS_PROVIDED = 'NO_SOURCE_FILE_RECORDS_PROVIDED',
	NO_FILES_IN_ARCHIVE = 'NO_FILES_IN_ARCHIVE',
	FILE_LIMIT_PER_PARENT_EXCEEDED = 'FILE_LIMIT_PER_PARENT_EXCEEDED',
}
